title: Alicia Zhang # your name (or website title) here
logo: "/images/Business Profile Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/alicia-zhang1/">LinkedIn</a> 
  <br>
  <a href="images/resume(7).pdf">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/alz425/">GitHub</a>  

  
theme: jekyll-theme-minimal
